name: Icon-builder

on:
  push:
    branches:
      - 'your-branches'

jobs:
  icon-build:
    name: build-icon
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - run: npm run build:publish